# Generated by Django 4.2.3 on 2023-07-24 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Arch_App', '0004_departement_dossier_fichier'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dossier',
            new_name='Dossiers',
        ),
    ]
