# Generated by Django 4.2.3 on 2023-07-24 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Arch_App', '0006_alter_departement_id_alter_dossiers_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dossiers',
            new_name='Dossier',
        ),
    ]
