# Generated by Django 4.2.3 on 2023-07-24 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Arch_App', '0009_auto_20230724_1454'),
    ]

    operations = [
    ]
