# Generated by Django 4.2.3 on 2023-07-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arch_App', '0011_auto_20230724_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='date',
            field=models.DateTimeField(default='2023-01-01'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
