# Generated by Django 4.2.3 on 2023-07-24 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Arch_App', '0012_dossier_date_dossier_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dossier',
            old_name='date',
            new_name='modification',
        ),
    ]
