# Generated by Django 4.2.3 on 2023-07-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arch_App', '0013_rename_date_dossier_modification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossier',
            name='modification',
            field=models.DateField(auto_now=True),
        ),
    ]
