# Generated by Django 4.2.3 on 2023-07-25 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Arch_App', '0014_alter_dossier_modification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fichier',
        ),
    ]
