# Generated by Django 4.2.3 on 2023-07-25 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Arch_App', '0015_delete_fichier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fichier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('chemin', models.CharField(max_length=200)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Arch_App.dossier')),
            ],
        ),
    ]
