# Generated by Django 4.2.3 on 2023-07-25 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arch_App', '0016_fichier'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichier',
            name='modification',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='fichier',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
