# Generated by Django 4.2.3 on 2023-07-31 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arch_App', '0017_fichier_modification_fichier_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature', models.CharField(max_length=100)),
                ('modification', models.DateField(auto_now=True)),
            ],
        ),
    ]
