# Generated by Django 4.2.3 on 2023-07-31 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arch_App', '0019_log_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='nom',
            field=models.CharField(default='fichier1.pdf', max_length=100),
            preserve_default=False,
        ),
    ]
