# Generated by Django 4.2.3 on 2023-09-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arch_App', '0020_log_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichier',
            name='modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='modification',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
